name: CI

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
  schedule:
  # Every Sunday at 1:30
  - cron: '30 1 * * 0'

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Build
      run: |
        cargo --locked build --all-features --profile release
    # - name: Setup MSYS2
    #   uses: msys2/setup-msys2@v2
    #   with:
    #     install: base-devel git
    # - name: Test
    #   shell: msys2 {0}
    #   env:
    #     STG_TEST_OPTS: "-v -i"
    #     STG_PROFILE: "release"
    #   run: |
    #     timeout 900s make -C t test

  full-suite:
    name: Build, Lints, Docs, Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Format checks
      run: |
        cargo --locked fmt --all --check
    - name: Clippy checks
      run: |
        cargo --locked clippy -- --deny warnings
    - name: API docs
      run: |
        cargo --locked rustdoc -- --deny warnings
    - name: Unit tests
      run: |
        cargo --locked test
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install asciidoc asciidoctor docbook-xsl-ns gnupg2 quilt xmlto
    - name: Build docs asciidoc
      env:
        STG_PROFILE: "dev"
      run: |
        make -j2 doc
    - name: Build docs asciidoctor
      env:
        STG_PROFILE: "dev"
        USE_ASCIIDOCTOR: "1"
      run: |
        make -j2 doc
    - name: Install HTML docs
      env:
        STG_PROFILE: "dev"
        USE_ASCIIDOCTOR: "1"
      run: |
        make -j2 htmldir="$GITHUB_WORKSPACE"/stgit-html install-html
    - name: Upload HTML docs
      uses: actions/upload-artifact@v3
      with:
        name: html-doc
        path: ${{ github.workspace }}/stgit-html
    - name: Integration tests
      env:
        STG_PROVE_OPTS: "--jobs=2"
        STG_TEST_OPTS: "--verbose-log"
        STG_PROFILE: "dev"
      run: |
        timeout 900s make prove
    - name: Show failures
      if: ${{ failure() }}
      run: |
        make -C t show-failure-results

  build-and-test:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            profile: release
            toolchain: stable
          - os: ubuntu-latest
            profile: dev
            toolchain: nightly
          - os: macos-latest
            profile: dev
            toolchain: stable
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      run: |
        cargo --locked build --all-features --profile ${{ matrix.profile }}
    - name: Install Test Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install quilt gnupg2
    - name: Install Test Dependencies (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        # coreutils provides the `timeout` command used to wrap `make` below.
        # gnu-sed is needed by some tests (e.g. t3400-pick.sh).
        brew install coreutils gnu-sed
        echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
        echo "$(brew --prefix)/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
    - name: Test
      env:
        STG_PROVE_OPTS: "--jobs=2"
        STG_TEST_OPTS: "--verbose-log"
        STG_PROFILE: ${{ matrix.profile }}
      run: |
        timeout 900s make -C t prove
    - name: Show Failures
      if: ${{ failure() }}
      run: |
        make -C t show-failure-results
